// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaIxjzyYzEcaK4ponzHLCMy5TABDGe3hk',
    appId: '1:593041982121:web:f68f1ad24e9181ef235fb8',
    messagingSenderId: '593041982121',
    projectId: 'chat-app-b866e',
    authDomain: 'chat-app-b866e.firebaseapp.com',
    storageBucket: 'chat-app-b866e.firebasestorage.app',
    measurementId: 'G-TCV9W7G8XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0l410YdMxaOSXazqmLf9QJL0K0MzZI54',
    appId: '1:593041982121:android:8406bd8685064b14235fb8',
    messagingSenderId: '593041982121',
    projectId: 'chat-app-b866e',
    storageBucket: 'chat-app-b866e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCDuOsXNU6LBA3gU-Ovzqu5rhsYB7CpH0',
    appId: '1:593041982121:ios:83e97aa8b86cb43a235fb8',
    messagingSenderId: '593041982121',
    projectId: 'chat-app-b866e',
    storageBucket: 'chat-app-b866e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCDuOsXNU6LBA3gU-Ovzqu5rhsYB7CpH0',
    appId: '1:593041982121:ios:83e97aa8b86cb43a235fb8',
    messagingSenderId: '593041982121',
    projectId: 'chat-app-b866e',
    storageBucket: 'chat-app-b866e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaIxjzyYzEcaK4ponzHLCMy5TABDGe3hk',
    appId: '1:593041982121:web:00d1efdd6be18e72235fb8',
    messagingSenderId: '593041982121',
    projectId: 'chat-app-b866e',
    authDomain: 'chat-app-b866e.firebaseapp.com',
    storageBucket: 'chat-app-b866e.firebasestorage.app',
    measurementId: 'G-MBT6SQVNZQ',
  );
}
